adding coverage details

diff --git a/.github/workflows/sonarqube.yml b/.github/workflows/sonarqube.yml
--- a/.github/workflows/sonarqube.yml
+++ b/.github/workflows/sonarqube.yml
@@ -11,14 +11,14 @@ on:
         - master
         - develop
         - 'releases/**'
-      types: 
+      types:
         - opened
         - synchronize
         - reopened
   
-name: Main Workflow
+  name: Main Workflow
   
-jobs:
+  jobs:
     sonarqube:
       runs-on: ubuntu-latest
       steps:
@@ -26,16 +26,35 @@ jobs:
           uses: actions/checkout@v4
           with:
             fetch-depth: 0
+  
         - name: Set up Java
           uses: actions/setup-java@v3
           with:
             distribution: 'temurin'
             java-version: '11'
+  
         - name: SonarQube Scan
-          uses: sonarsource/sonarqube-scan-action@v2.1.0 # Replace with the latest version
+          uses: sonarsource/sonarqube-scan-action@v2.1.0
           env:
             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-            SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
+            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
             SONAR_SCANNER_OPTS: '-Xmx1024m'
             SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
+  
+        - name: Check SonarQube Quality Gate
+          env:
+            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+          run: |
+            status=$(curl -s "${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=SNHS1998_SonarQube-GitHubActions" -u "${SONAR_TOKEN}:")
+            coverage=$(echo "$status" | jq -r '.projectStatus.conditions[] | select(.metricKey == "coverage") | .actualValue')
+  
+            echo "Current Coverage: $coverage%"
+  
+            if (( $(echo "$coverage < 80" | bc -l) )); then
+              echo "Code coverage is less than 80%. Failing the build."
+              exit 1
+            else
+              echo "Code coverage is sufficient. Proceeding with the build."
+            fi
   
